# -*- coding: utf-8 -*-
"""Abalone_RandomForest_and_VotingRegressor_js

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JGZ-0CZoNp3L6h66CZ6a32VU683hd9Qz
"""

# Step 1 - Import Libraries
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from sklearn import tree

# Step 2 - Read data into a dataframe
names = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']
df = pd.read_csv('/content/abalone.data', names=names, sep=',')

df.head()

df = df.drop('Sex', axis=1)

df.columns

# Step 4 - Define X and y
X = df[['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight']]
y = df['Rings']

X

y

# Step 5 - Split X and y into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=45)

#Define object of RandomForestRegressor
clf = RandomForestRegressor(n_estimators=100, random_state=42)

#fit the algorithm to X_train,y_train
clf.fit(X_train, y_train)

fig,axes = plt.subplots(nrows=1,ncols=1,figsize=(4,4),dpi=800)
tree.plot_tree(clf.estimators_[0],feature_names=X.columns,filled=True, max_depth=3)

fig,axes = plt.subplots(nrows=1,ncols=5,figsize=(10,2),dpi=900)
for i in range(0,5):
    tree.plot_tree(clf.estimators_[i],feature_names=X.columns,filled=True,ax=axes[i], max_depth=3)

clf.score(X_train,y_train)

# Evaluate the RandomForestRegressor on the test set
test_score = clf.score(X_test, y_test)
print(f"R-squared score on the test set: {test_score}")

"""## Summary of Random Forest Regressor Work

Here's a summary of the steps taken and the results obtained using the Decision Tree Regressor model on the abalone dataset:

1.  **Data Preparation**: The abalone dataset was loaded, and the 'Sex' column was dropped as it was not used in this model. The features (`X`) and target variable ('Rings', `y`) were defined. The data was split into training and testing sets.

2.  **Model Training**: A `RandomForestRegressor` model was initialized and trained on the training data (`X_train`, `y_train`). (Note: While the request mentions Decision Tree Regressor, the code executed used a `RandomForestRegressor`. This summary reflects the executed code.)

3.  **Model Visualization**: Attempts were made to visualize the decision trees within the Random Forest. Due to the complexity of the full trees, the visualization was simplified by plotting individual trees with a limited depth (max_depth=3).

4.  **Training Score**: The R-squared score on the training data was calculated as 0.936. This indicates that the model fits the training data very well.

5.  **Test Score**: The R-squared score on the test data was calculated as 0.505. This score is significantly lower than the training score.

**Interpretation of Results**:

*   The high training score suggests that the model has learned the patterns in the training data effectively.
*   The considerably lower test score indicates that the model may be **overfitting** the training data. Overfitting occurs when a model learns the training data too well, including noise and specific patterns that do not generalize to new, unseen data. This results in poorer performance on the test set compared to the training set. The model is not as effective at predicting the number of rings for new abalone data.

**Next Steps (Suggested)**:

*   Address the overfitting issue by techniques such as:
    *   Tuning hyperparameters of the `RandomForestRegressor` (e.g., reducing `max_depth`, increasing `min_samples_leaf`).
    *   Using cross-validation during training.
    *   Exploring other regression models.
*   Analyze feature importance to understand which features are most influential in the predictions.
*   Evaluate the model using other regression metrics (e.g., Mean Absolute Error, Mean Squared Error).
"""

!pip install dtreeviz

import dtreeviz

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
dt.fit(X_train,y_train)

from sklearn.tree import DecisionTreeRegressor
import dtreeviz

# Train a new Decision Tree Regressor with max_depth=3
dt_simplified = DecisionTreeRegressor(max_depth=3)
dt_simplified.fit(X_train, y_train)

# Visualize the simplified tree using dtreeviz
viz_model_simplified = dtreeviz.model(dt_simplified,
                                      X_train,
                                      y_train,
                                      feature_names=X.columns,
                                      target_name='Rings')

viz_model_simplified.view(fontname="monospace")

#import all the required libraries for voting classifier to use with abalone data
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, VotingRegressor
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression # Import Linear Regression
from sklearn.ensemble import RandomForestRegressor # RandomForestRegressor is already imported, but good to be explicit
from sklearn.svm import SVR # Import Support Vector Regressor

# Read abalone data into data frame
names = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']
df = pd.read_csv('/content/abalone.data', names=names, sep=',')

# Preprocess data
df = df.drop('Sex', axis=1)

df.columns

# Define X and y
X = df[['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight']]
y = df['Rings']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

X_train

y_train

from sklearn.linear_model import LinearRegression # Import Linear Regression
from sklearn.ensemble import RandomForestRegressor # RandomForestRegressor is already imported, but good to be explicit
from sklearn.svm import SVR # Import Support Vector Regressor

algos = []
algos.append(('lr',LinearRegression())) # Replaced LogisticRegression with LinearRegression
algos.append(('rf',RandomForestRegressor())) # Replaced RandomForestClassifier with RandomForestRegressor
algos.append(('svr',SVR())) # Replaced SVC with SVR
algos

voting = VotingRegressor(algos)
voting.fit(X_train,y_train)

voting.score(X_train,y_train)

# Evaluate the VotingRegressor on the test set
voting_test_score = voting.score(X_test, y_test)
print(f"R-squared score on the test set for Voting Regressor: {voting_test_score}")

# Show the performance of individual regression models
for name, model in algos:
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
    print(f"R-squared score for {name}: {score}")

# Predict using the VotingRegressor
# The input should be a 2D array-like structure with 7 features (matching X)
y_pred = voting.predict([[0.5, 0.4, 0.15, 0.7, 0.3, 0.15, 0.2]])
y_pred

for name, model in algos: # Use the 'model' variable from the loop
    model.fit(X_train,y_train)
    y_train_pred = model.predict([[0.5, 0.4, 0.15, 0.7, 0.3, 0.15, 0.2]]) # Corrected from clf.predict to model.predict
    print(f"Prediction from {name}: {y_train_pred}") # Added name for clarity

voting = VotingRegressor(algos)
voting.fit(X_train,y_train)

"""## Summary of Voting Regressor

Here's a summary of the steps taken and the results obtained using the Voting Regressor model on the abalone dataset:

1.  **Import Libraries**: Necessary libraries for regression models and the `VotingRegressor` were imported.
2.  **Data Preparation**: The abalone dataset was loaded, preprocessed by dropping the 'Sex' column, and split into training and testing sets, similar to the Random Forest section.
3.  **Define Base Models**: Instead of classification models, a list of regression models (`LinearRegression`, `RandomForestRegressor`, and `SVR`) was defined to be used in the voting ensemble.
4.  **Train Voting Regressor**: A `VotingRegressor` model was initialized with the defined regression algorithms and trained on the training data (`X_train`, `y_train`).
5.  **Evaluate Voting Regressor**: The R-squared score of the `VotingRegressor` was calculated on the test set (`X_test`, `y_test`), resulting in a score of 0.566.
6.  **Evaluate Individual Models**: The R-squared scores of the individual regression models within the ensemble were also calculated on the test set to compare their performance:
    *   Linear Regression: 0.533
    *   Random Forest Regressor: 0.527
    *   SVR: 0.531
7.  **Prediction**: The `VotingRegressor` model was used to make a prediction on a sample input, resulting in a predicted value.

**Interpretation**:

The `VotingRegressor` achieved a slightly higher R-squared score (0.566) on the test set compared to the individual `RandomForestRegressor` (0.505) trained earlier. This suggests that combining the predictions of different regression models in a voting ensemble can potentially lead to improved generalization performance on this dataset. The individual model scores show the performance of each component of the ensemble.
"""

